#!/usr/bin/env python3
"""Post-process recovery run reps into autoresearch summary.json files.

Reads per-rep JSON files from:
  results/autoresearch/phase_c/exp001_recovery_phaseA_winner/
  results/autoresearch/phase_c/exp002_recovery_closet_sonnet/

Computes composite mean/sd for each, compares against the Phase C baseline
(exp000_baseline), and writes summary.json with accepted=True for each
experiment that improves on baseline, accepted=False otherwise.

Run after scripts/run_recovery_tunable.sh completes.
"""
from __future__ import annotations

import json
import statistics
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPTS_DIR = REPO_ROOT / "scripts"
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

from autoresearch import composite_from_track_result  # noqa: E402

PHASE_C_DIR = REPO_ROOT / "results" / "autoresearch" / "phase_c"
BASELINE_COMPOSITE = 0.7402  # from exp000_baseline/summary.json
SD_FLOOR = 0.005
ABS_DELTA_FLOOR = 0.01


def _utc_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _load_reps(exp_dir: Path) -> list[dict]:
    """Load axis stats from all rep JSON files in exp_dir."""
    reps = []
    for path in sorted(exp_dir.glob("*.json")):
        if path.name == "summary.json" or path.name == "knobs.json":
            continue
        try:
            payload = json.loads(path.read_text())
        except (json.JSONDecodeError, OSError):
            continue
        axis = composite_from_track_result(payload)
        axis["spend_usd"] = payload.get("spend_usd", 0.0)
        axis["wall_seconds"] = payload.get("wall_seconds", 0.0)
        axis["result_path"] = (
            str(path.relative_to(REPO_ROOT))
            if path.is_relative_to(REPO_ROOT)
            else str(path)
        )
        reps.append(axis)
    return reps


def _build_summary(
    exp_id: str,
    knobs: dict,
    reps: list[dict],
    baseline_composite: float,
) -> dict:
    if not reps:
        raise ValueError(f"No reps found for {exp_id}")
    composites = [r["composite"] for r in reps]
    comp_mean = statistics.fmean(composites)
    comp_sd = statistics.pstdev(composites) if len(composites) > 1 else 0.0
    delta = comp_mean - baseline_composite
    required = max(1.5 * SD_FLOOR, ABS_DELTA_FLOOR)
    if delta >= required:
        accepted = True
        reason = (
            f"accepted: delta {delta:+.4f} >= required {required:.4f} "
            f"vs Phase C baseline {baseline_composite:.4f}"
        )
    else:
        accepted = False
        reason = (
            f"rejected: delta {delta:+.4f} < required {required:.4f} "
            f"vs Phase C baseline {baseline_composite:.4f}"
        )
    return {
        "experiment_id": exp_id,
        "knobs": knobs,
        "reps": reps,
        "composite_mean": comp_mean,
        "composite_sd": comp_sd,
        "accepted": accepted,
        "reason": reason,
        "delta_vs_accepted": delta,
        "created_at": _utc_iso(),
        "rationale": (
            "Article 2 Phase C recovery: porting Phase A winner to Track C "
            "and comparing against baseline. Not generated by the autoresearch "
            "proposer LLM — these are pre-specified configs."
        ),
        "reasoning": (
            f"Recovery config {exp_id}: {len(reps)} reps, "
            f"composite mean {comp_mean:.4f} ± {comp_sd:.4f}"
        ),
    }


RECOVERY_CONFIGS: list[tuple[str, dict]] = [
    (
        "exp001_recovery_phaseA_winner",
        {
            "extract_mode": "exchange",
            "chunk_leading_prefix": "> ",
            "top_k": 30,
            "max_distance": 0.0,
            "closet_llm_enabled": True,
            "closet_llm_model": "anthropic/claude-haiku-4.5",
            "closet_llm_sample": 0,
        },
    ),
    (
        "exp002_recovery_closet_sonnet",
        {
            "extract_mode": "exchange",
            "chunk_leading_prefix": "> ",
            "top_k": 30,
            "max_distance": 0.0,
            "closet_llm_enabled": True,
            "closet_llm_model": "anthropic/claude-sonnet-4.6",
            "closet_llm_sample": 0,
        },
    ),
]


def main() -> int:
    # Load baseline composite from disk (authoritative).
    baseline_path = PHASE_C_DIR / "exp000_baseline" / "summary.json"
    if baseline_path.exists():
        baseline_data = json.loads(baseline_path.read_text())
        baseline_composite = float(baseline_data["composite_mean"])
        print(f"Baseline composite from disk: {baseline_composite:.4f}")
    else:
        baseline_composite = BASELINE_COMPOSITE
        print(f"Baseline path not found — using hardcoded {baseline_composite:.4f}")

    generated = 0
    for exp_dirname, knobs in RECOVERY_CONFIGS:
        exp_dir = PHASE_C_DIR / exp_dirname
        if not exp_dir.exists():
            print(f"SKIP {exp_dirname}: directory does not exist yet")
            continue
        reps = _load_reps(exp_dir)
        if not reps:
            print(f"SKIP {exp_dirname}: no rep files found")
            continue
        summary = _build_summary(exp_dirname, knobs, reps, baseline_composite)
        summary_path = exp_dir / "summary.json"
        summary_path.write_text(json.dumps(summary, indent=2))
        print(
            f"Wrote {summary_path.relative_to(REPO_ROOT)}: "
            f"composite={summary['composite_mean']:.4f} ± {summary['composite_sd']:.4f} "
            f"accepted={summary['accepted']} ({summary['reason'][:60]}...)"
        )
        generated += 1

    if generated == 0:
        print("No summaries generated. Did the recovery reps complete?")
        return 1
    print(f"Done. Generated {generated} summary files.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
